name: gym-duckietown
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.7
    - pytorch
    - torchvision
    - pyzmq
    - numpy
    - pyyaml=3.12
    - pip:
        - gym
        - pyglet==1.5.27
        - opencv-python
        - scikit-image
        - carnivalmirror
        - -r requirements.txt
